In [50]:
import os
import json
import requests
import pandas as pd
os.listdir()

['.git',
 '.ipynb_checkpoints',
 'altmetrics-harvester.ipynb',
 'last_quarter.csv',
 'last_quarter.json',
 'one_year.csv',
 'one_year.json',
 'README.md']

In [51]:
d = json.loads(requests.get('https://api.altmetric.com/v1/citations/1y?doi_prefix=10.5519').text)
del d['query']
with open('one_year.json', 'w') as data_file:
    data = json.dump(d, data_file)

In [52]:
df1 = pd.read_json('one_year.json')
df1

                                              results
0   {'title': 'The 2016 release of the PREDICTS da...
1   {'title': 'iCollections', 'doi': '10.5519/0038...
2   {'title': 'Collection specimens', 'doi': '10.5...
3   {'title': 'Insect Pollinators Initiative', 'do...
4   {'title': 'Mark My Bird', 'doi': '10.5519/0025...
5   {'title': 'Sloane Herbarium', 'doi': '10.5519/...
6   {'title': 'Ludlow Museum Fossils in Shropshire...
7   {'title': 'Phthiraptera collection', 'doi': '1...
8   {'title': 'Mark My Bird', 'doi': '10.5519/0005...
9   {'title': 'NHM Interactions Bank', 'doi': '10....
10  {'title': 'Clayton Herbarium', 'doi': '10.5519...

In [53]:
results = pd.read_json( (df1['results']).to_json(), orient='index')
images = pd.read_json( (results['images']).to_json(), orient='index')
full_results = pd.concat([results, images], axis=1, join_axes=[results.index])
full_results

,added_on,altmetric_id,authors,cited_by_accounts_count,cited_by_feeds_count,cited_by_msm_count,cited_by_posts_count,cited_by_tweeters_count,cohorts,details_url,...,readers_count,schema,score,title,tq,type,url,large,medium,small
0,1484945804,15616163,[Lawrence N Hudson; Tim Newbold; Sara Contu; S...,159,1.0,NaN,197,158,"{'pub': 105, 'sci': 49, 'com': 4}",http://www.altmetric.com/details.php?citation_...,...,1,1.5.4,112.942,The 2016 release of the PREDICTS database,[#PREDICTS global #biodiversity #database proj...,article,http://dx.doi.org/10.5519/0066354,https://badges.altmetric.com/?size=180&score=1...,https://badges.altmetric.com/?size=100&score=1...,https://badges.altmetric.com/?size=64&score=11...
1,1490001929,17827714,[Gordon L J Paterson; Sara Albuquerque; Vladim...,65,NaN,NaN,74,65,"{'sci': 13, 'pub': 50, 'com': 2}",http://www.altmetric.com/details.php?citation_...,...,0,1.5.4,48.000,iCollections,[We provide #OpenAcess to our digitised UK Iri...,article,http://dx.doi.org/10.5519/0038559,https://badges.altmetric.com/?size=180&score=4...,https://badges.altmetric.com/?size=100&score=4...,https://badges.altmetric.com/?size=64&score=48...
10,1485265758,15737317,[Charlie Jarvis],1,NaN,NaN,1,1,{'sci': 1},http://www.altmetric.com/details.php?citation_...,...,0,1.5.4,1.000,Clayton Herbarium,NaN,article,http://dx.doi.org/10.5519/0063794,https://badges.altmetric.com/?size=180&score=1...,https://badges.altmetric.com/?size=100&score=1...,https://badges.altmetric.com/?size=64&score=1&...
2,1485265780,15737327,[Natural History Museum],21,NaN,1.0,21,20,"{'pub': 17, 'sci': 1, 'com': 2}",http://www.altmetric.com/details.php?citation_...,...,1,1.5.4,25.250,Collection specimens,[Starting #advent with an illustration from Hi...,article,http://dx.doi.org/10.5519/0002965,https://badges.altmetric.com/?size=180&score=2...,https://badges.altmetric.com/?size=100&score=2...,https://badges.altmetric.com/?size=64&score=26...
3,1490970197,18352776,"[Professor Graham N Stone, Professor Alfried V...",13,1.0,NaN,18,12,{'pub': 12},http://www.altmetric.com/details.php?citation_...,...,0,1.5.4,14.730,Insect Pollinators Initiative,[The #IPIArchive data is available via #openac...,article,http://dx.doi.org/10.5519/0062900,https://badges.altmetric.com/?size=180&score=1...,https://badges.altmetric.com/?size=100&score=1...,https://badges.altmetric.com/?size=64&score=15...
4,1486632170,16252778,[Gavin H. Thomas (University of Sheffield & Na...,16,NaN,NaN,16,16,"{'pub': 13, 'sci': 3}",http://www.altmetric.com/details.php?citation_...,...,0,1.5.4,11.200,Mark My Bird,[The mark my bird dataset is now on the data p...,article,http://dx.doi.org/10.5519/0025663,https://badges.altmetric.com/?size=180&score=1...,https://badges.altmetric.com/?size=100&score=1...,https://badges.altmetric.com/?size=64&score=12...
5,1504187631,24571670,[Charlie Jarvis],2,1.0,NaN,2,1,{'pub': 1},http://www.altmetric.com/details.php?citation_...,...,0,1.5.4,8.080,Sloane Herbarium,NaN,article,http://dx.doi.org/10.5519/0081520,https://badges.altmetric.com/?size=180&score=9...,https://badges.altmetric.com/?size=100&score=9...,https://badges.altmetric.com/?size=64&score=9&...
6,1494602749,20076644,"[Daniel Lockett, Jackie Tweddle]",10,NaN,NaN,10,10,"{'pub': 8, 'sci': 2}",http://www.altmetric.com/details.php?citation_...,...,0,1.5.4,7.950,Ludlow Museum Fossils in Shropshire Project data,NaN,article,http://dx.doi.org/10.5519/0015223,https://badges.altmetric.com/?size=180&score=8...,https://badges.altmetric.com/?size=100&score=8...,https://badges.altmetric.com/?size=64&score=8&...
7,1503749404,24347051,"[Olha Schedrina, Louise Allan, Paul Brown, Lau...",3,NaN,NaN,3,3,{'pub': 3},http://www.altmetric.com/details.php?citation_...,...,0,1.5.4,2.500,Phthiraptera collection,NaN,article,http://dx.doi.org/10.5519/0096731,https://badges.altmetric.com/?size=180&score=3...,https://badges.altmetric.com/?size=100&score=3...,https://badges.altmetric.com/?size=64&score=3&...
8,1486484774,16203308,[Gavin H. Thomas (University of Sheffield & Na...,4,NaN,NaN,4,4,"{'pub': 3, 'sci': 1}",http://www.altmetric.com/details.php?citation_...,...,0,1.5.4,2.000,Mark My Bird,[Plus all the data open to all],article,http://dx.doi.org/10.5519/0005413,https://badges.altmetric.com/?size=180&score=2...,https://badges.altmetric.com/?size=100&score=2...,https://badges.altmetric.com/?size=64&score=2&...
9,1488820840,17055870,[Ed Baker; Ian J. Kitching; George W. Beccalon...,2,NaN,NaN,2,2,{'pub': 2},http://www.altmetric.com/details.php?citation_...,...,0,1.5.4,1.850,NHM Interactions Bank,NaN,article,http://dx.doi.org/10.5519/0060767,https://badges.altmetric.com/?size=180&score=2...,https://badges.altmetric.com/?size=100&score=2...,https://badges.altmetric.com/?size=64&score=2&...

In [55]:
full_results.to_csv('one_year.csv')
os.listdir()

['.git',
 '.ipynb_checkpoints',
 'altmetrics-harvester.ipynb',
 'last_quarter.csv',
 'last_quarter.json',
 'one_year.csv',
 'one_year.json',
 'README.md']